version: '3'

services:

  database:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - data:/data/db

  app:
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - database
    environment:
      # no auth required, which is secure because mongo is only visible locally
      - DATABASE=mongodb://database/rsvp?retryWrites=true
      # forward from host environment
      - DOWNLOAD_CREDENTIALS

volumes:
  data:
